# Copy Archipelago INI files to exe directory.
# Invoked at build time with -DEXE_DIR=<path> -DARCHIPELAGO_INI=<path>
# -DARCHIPELAGO_CHALLENGE_PROTECTION_INI=<path> -DUNLOCKABLE_CHECKS_INI=<path>
if(NOT EXE_DIR)
  message(FATAL_ERROR "CopyIniToExeDir.cmake: EXE_DIR not set")
endif()
set(OUT_DIR "${EXE_DIR}/Data/INI")
message(STATUS "CopyIniToExeDir: copying INI files to ${OUT_DIR}")
file(MAKE_DIRECTORY "${OUT_DIR}")
if(ARCHIPELAGO_INI AND EXISTS "${ARCHIPELAGO_INI}")
  file(COPY "${ARCHIPELAGO_INI}" DESTINATION "${OUT_DIR}")
  message(STATUS "CopyIniToExeDir: copied Archipelago.ini -> ${OUT_DIR}")
endif()
if(ARCHIPELAGO_CHALLENGE_PROTECTION_INI AND EXISTS "${ARCHIPELAGO_CHALLENGE_PROTECTION_INI}")
  file(COPY "${ARCHIPELAGO_CHALLENGE_PROTECTION_INI}" DESTINATION "${OUT_DIR}")
  message(STATUS "CopyIniToExeDir: copied ArchipelagoChallengeUnitProtection.ini -> ${OUT_DIR}")
endif()
if(UNLOCKABLE_CHECKS_INI AND EXISTS "${UNLOCKABLE_CHECKS_INI}")
  file(COPY "${UNLOCKABLE_CHECKS_INI}" DESTINATION "${OUT_DIR}")
  message(STATUS "CopyIniToExeDir: copied UnlockableChecksDemo.ini -> ${OUT_DIR}")
endif()
